INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AACG','ATA Creativity Global','Depositary Receipt','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AACG','ATA Creativity Global','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AACQ','Artius Acquisition Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAL','American Airlines Group Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAME','Atlantic American Corporation','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAME','Atlantic American Corp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAOI','Applied Optoelectronics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAOI','Applied Optoelectronics, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAON','AAON Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAPL','Apple Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAWW','Atlas Air Worldwide Holdings Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('AAXN','Axon Enterprise Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCB','Ameris Bancorp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCL','AbCellera Biologics Inc','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABCM','Abcam PLC','American Depositary Receipt','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABEO','Abeona Therapeutics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABEO','Abeona Therapeutics Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABGI','ABG Acquisition Corp. I','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABIO','ARCA biopharma, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABIO','ARCA biopharma Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABMD','ABIOMED Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABNB','Airbnb, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABST','Absolute Software Corporation','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABTX','Allegiance Bancshares Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ABUS','Arbutus Biopharma Corp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAC','Acies Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAC','Acies Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAD','ACADIA Pharmaceuticals Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAH','Atlantic Coastal Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAM','Acamar Partners Acquisition Corp','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACAMU','Acamar Partners Acquisition Corp','Unit','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACBA','Ace Global Business Acquisition Limited','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACBI','Atlantic Capital Bancshares Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACCD','Accolade Inc','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACER','Acer Therapeutics Inc','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACER','Acer Therapeutics Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACET','Adicet Bio, Inc.','Common Stock','webSite','United States','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACET','Adicet Bio, Inc.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACEV','ACE Convergence Acquisition Corp.','EQUITY','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACEV','ACE Convergence Acquisition Corp','Common Stock','webSite','United States of America','Dow Jones');
INSERT INTO EMPRESA (empresa_id,nome,categoria,website,localizacao,mercado_codigo) VALUES('ACGL','Arch Capital Group Ltd','Common Stock','webSite','United States','Dow Jones');
